version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/images/node/Dockerfile
    tty: true
    volumes:
      - ./:/var/www
    env_file:
      - ./.docker/dev/.env.dev
    ports:
      - 3000:3000
      - 5555:5555
      - 8000:8000
